class ShipmentConfig
  LA_POSTE = 'LP'
  MONDIAL_RELAY = 'MR'
  S_SIZE = 'S'
  M_SIZE = 'M'
  L_SIZE = 'L'

  LP_S = 1.5
  LP_M = 4.9
  LP_L = 6.9
  MR_S = 2
  MR_M = 3
  MR_L = 4

  AVAILABLE_SHIPMENTS = [ LA_POSTE, MONDIAL_RELAY ]
  AVAILABLE_SIZES = [ S_SIZE, M_SIZE, L_SIZE ]

  DATE_DELIMITER = '-'
  MAX_MONTHLY_DISCOUNT = 10.00

  FREE_SHIPMENT_ON = L_SIZE
  FREE_SHIPMENT_PROVIDER = LA_POSTE
  FREE_SHIPMENT_PRICE = LP_L
  FREE_SHIPMENT_AFTER_ODERS = 3

  LOWEST_PRICE_ON = S_SIZE
  LOWEST_PRICES = { "#{LA_POSTE}": LP_S, "#{MONDIAL_RELAY}": MR_S }
end